services:
  locallibrary-frontend-postgresdb:
    image: postgres:16.3-bookworm
    container_name: locallibrary-frontend-postgresdb
    volumes:
      - pg-data-locallibrary-frontend:/var/lib/postgresql/data
      - ./postgres-initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=locallibrary_frontend
      - POSTGRES_USER=locallibrary_frontend
      - POSTGRES_PASSWORD=locallibrary_frontend
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "dbname=locallibrary_frontend user=locallibrary_frontend"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5432
  locallibrary-frontend-http-server:
    depends_on:
      locallibrary-frontend-postgresdb:
        condition: service_healthy
    build:
      context: ../frontend
    container_name: locallibrary-frontend-http-server
    environment:
      POSTGRES_URI: postgresql+psycopg://locallibrary_frontend:locallibrary_frontend@locallibrary-frontend-postgresdb:5432/locallibrary_frontend
      DEBUG: true
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID not set}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET not set}
      JWT_ECDSA_PRIVATE_KEY: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNQc3I5ZTRMRDAreFpJUzFJVnR6ellabC9ZcFFqOVpHcWM0VlVtWHNIUUVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZzJKVjgvRVVpK2Z6Q3hsQ2hnTUhyOFhuR0pidlRlK1N1VTJaVWd3OW1yejViK3NUMGEvRwp6c1I3QXA5MG1FYlR2dW83dXpWMjZ2VzhsOUZMVmhMUFV3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      JWT_ECDSA_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZzJKVjgvRVVpK2Z6Q3hsQ2hnTUhyOFhuR0pidgpUZStTdVUyWlVndzltcno1YitzVDBhL0d6c1I3QXA5MG1FYlR2dW83dXpWMjZ2VzhsOUZMVmhMUFV3PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    ports:
      - 8000:80
  locallibrary-frontend-grpc-server:
    depends_on:
      locallibrary-frontend-postgresdb:
        condition: service_healthy
    build:
      context: ../frontend
    container_name: locallibrary-frontend-grpc-server
    environment:
      POSTGRES_URI: postgresql+psycopg://locallibrary_frontend:locallibrary_frontend@locallibrary-frontend-postgresdb:5432/locallibrary_frontend
      DEBUG: true
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID not set}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET not set}
      JWT_ECDSA_PRIVATE_KEY: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNQc3I5ZTRMRDAreFpJUzFJVnR6ellabC9ZcFFqOVpHcWM0VlVtWHNIUUVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZzJKVjgvRVVpK2Z6Q3hsQ2hnTUhyOFhuR0pidlRlK1N1VTJaVWd3OW1yejViK3NUMGEvRwp6c1I3QXA5MG1FYlR2dW83dXpWMjZ2VzhsOUZMVmhMUFV3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      JWT_ECDSA_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZzJKVjgvRVVpK2Z6Q3hsQ2hnTUhyOFhuR0pidgpUZStTdVUyWlVndzltcno1YitzVDBhL0d6c1I3QXA5MG1FYlR2dW83dXpWMjZ2VzhsOUZMVmhMUFV3PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    ports:
      - 50051
    command: locallibrary-frontend-grpc-server
  locallibrary-admin-http-server:
    build:
      context: ../admin
    container_name: locallibrary-admin-http-server
    ports:
      - 8001:80
    command: >-
      /bin/server -environment=development
      -frontend-grpc-server-address=locallibrary-frontend-grpc-server:50051

volumes:
  pg-data-locallibrary-frontend:
