services:
  locallibrary-frontend-postgresdb:
    image: postgres:16.3-bookworm
    container_name: locallibrary-frontend-postgresdb
    volumes:
      - pg-data-locallibrary-frontend:/var/lib/postgresql/data
      - ./postgres-initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=locallibrary_frontend
      - POSTGRES_USER=locallibrary_frontend
      - POSTGRES_PASSWORD=locallibrary_frontend
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "dbname=locallibrary_frontend user=locallibrary_frontend"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5432
  locallibrary-frontend-http-server:
    depends_on:
      locallibrary-frontend-postgresdb:
        condition: service_healthy
    build:
      context: ../frontend
    container_name: locallibrary-frontend-http-server
    environment:
      POSTGRES_URI: postgresql+psycopg://locallibrary_frontend:locallibrary_frontend@locallibrary-frontend-postgresdb:5432/locallibrary_frontend
      DEBUG: true
    ports:
      - 8000:80
  locallibrary-frontend-grpc-server:
    depends_on:
      locallibrary-frontend-postgresdb:
        condition: service_healthy
    build:
      context: ../frontend
    container_name: locallibrary-frontend-grpc-server
    environment:
      POSTGRES_URI: postgresql+psycopg://locallibrary_frontend:locallibrary_frontend@locallibrary-frontend-postgresdb:5432/locallibrary_frontend
      DEBUG: true
    ports:
      - 50051
    command: locallibrary-frontend-grpc-server
  locallibrary-admin-http-server:
    build:
      context: ../admin
    container_name: locallibrary-admin-http-server
    ports:
      - 8001:80
    command: >-
      /bin/server -environment=development
      -frontend-grpc-server-address=locallibrary-frontend-grpc-server:50051

volumes:
  pg-data-locallibrary-frontend:
