# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from locallibrary_frontend_grpc import frontend_pb2 as locallibrary__frontend__grpc_dot_frontend__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in locallibrary_frontend_grpc/frontend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocalLibraryFrontendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBook = channel.unary_unary(
                '/LocalLibraryFrontend/AddBook',
                request_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.AddBookRequest.SerializeToString,
                response_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.BookDetail.FromString,
                _registered_method=True)
        self.RemoveBook = channel.unary_unary(
                '/LocalLibraryFrontend/RemoveBook',
                request_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.RemoveBookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/LocalLibraryFrontend/GetUser',
                request_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.GetUserRequest.SerializeToString,
                response_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.UserDetail.FromString,
                _registered_method=True)
        self.ListBorrowedBooks = channel.unary_unary(
                '/LocalLibraryFrontend/ListBorrowedBooks',
                request_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.ListGenericResourceRequest.SerializeToString,
                response_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.BookList.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/LocalLibraryFrontend/ListUsers',
                request_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.ListGenericResourceRequest.SerializeToString,
                response_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.UserList.FromString,
                _registered_method=True)


class LocalLibraryFrontendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBook(self, request, context):
        """Add a book to the library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBook(self, request, context):
        """Remove a book from the library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Get a user and the books that they have borrowed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowedBooks(self, request, context):
        """List borrowed books
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """List users enrolled in the library.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalLibraryFrontendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.AddBookRequest.FromString,
                    response_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.BookDetail.SerializeToString,
            ),
            'RemoveBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBook,
                    request_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.RemoveBookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.GetUserRequest.FromString,
                    response_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.UserDetail.SerializeToString,
            ),
            'ListBorrowedBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowedBooks,
                    request_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.ListGenericResourceRequest.FromString,
                    response_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.BookList.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=locallibrary__frontend__grpc_dot_frontend__pb2.ListGenericResourceRequest.FromString,
                    response_serializer=locallibrary__frontend__grpc_dot_frontend__pb2.UserList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LocalLibraryFrontend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LocalLibraryFrontend', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocalLibraryFrontend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocalLibraryFrontend/AddBook',
            locallibrary__frontend__grpc_dot_frontend__pb2.AddBookRequest.SerializeToString,
            locallibrary__frontend__grpc_dot_frontend__pb2.BookDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocalLibraryFrontend/RemoveBook',
            locallibrary__frontend__grpc_dot_frontend__pb2.RemoveBookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocalLibraryFrontend/GetUser',
            locallibrary__frontend__grpc_dot_frontend__pb2.GetUserRequest.SerializeToString,
            locallibrary__frontend__grpc_dot_frontend__pb2.UserDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowedBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocalLibraryFrontend/ListBorrowedBooks',
            locallibrary__frontend__grpc_dot_frontend__pb2.ListGenericResourceRequest.SerializeToString,
            locallibrary__frontend__grpc_dot_frontend__pb2.BookList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocalLibraryFrontend/ListUsers',
            locallibrary__frontend__grpc_dot_frontend__pb2.ListGenericResourceRequest.SerializeToString,
            locallibrary__frontend__grpc_dot_frontend__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
