"""add id field to user

Revision ID: 0d8edd9951de
Revises: a3e0f769c5e8
Create Date: 2025-01-22 00:26:44.944983

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0d8edd9951de"
down_revision: str | None = "a3e0f769c5e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("id", postgresql.CITEXT(), nullable=True))
    op.create_unique_constraint(op.f("uq_user_id"), "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_id"), "user", type_="unique")
    op.drop_column("user", "id")
    # ### end Alembic commands ###
