"""make user names nullable

Revision ID: 46da80faef2c
Revises: 52dea6bc515f
Create Date: 2025-01-22 13:27:16.929630

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "46da80faef2c"
down_revision: str | None = "52dea6bc515f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "first_name", existing_type=postgresql.CITEXT(), nullable=True
    )
    op.alter_column(
        "user", "last_name", existing_type=postgresql.CITEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "last_name", existing_type=postgresql.CITEXT(), nullable=False
    )
    op.alter_column(
        "user", "first_name", existing_type=postgresql.CITEXT(), nullable=False
    )
    # ### end Alembic commands ###
