"""add refresh_tokens table

Revision ID: 52dea6bc515f
Revises: 0d8edd9951de
Create Date: 2025-01-22 02:33:47.377209

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "52dea6bc515f"
down_revision: str | None = "0d8edd9951de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("refresh_token", postgresql.CITEXT(), nullable=False),
        sa.Column("provider", postgresql.CITEXT(), nullable=False),
        sa.Column("user_id", postgresql.CITEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_refresh_token_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
