#
name: Publish admin Docker image
on:
  push:
    branches:
      - main
    paths:
      - 'admin/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}-admin"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Add build args to environment variables
        run: |
          echo "BUILDTIME=$(date --iso-8601=seconds)" >> "$GITHUB_ENV"
          echo "APP_VERSION=$(git describe --always --dirty --tags --long)" >> "$GITHUB_ENV"


      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: admin
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ env.BUILDTIME }}
            APP_VERSION=${{ env.APP_VERSION }}
