name: Frontend QA

on:
  pull_request:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  workflow_dispatch:

env:
  JWT_ECDSA_PUBLIC_KEY: ${{ secrets.JWT_ECDSA_PUBLIC_KEY }}
  JWT_ECDSA_PRIVATE_KEY: ${{ secrets.JWT_ECDSA_PRIVATE_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}


jobs:

  check-qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: frontend/pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        working-directory: frontend
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install --without test

      - name: Check black formatting
        working-directory: frontend
        run: poetry run black .

      - name: Check ruff
        working-directory: frontend
        run: poetry run ruff check .

      - name: Check pyright
        working-directory: frontend
        run: poetry run pyright src/
