name: "Protocol Bufffer Stubs Generation"
on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'proto/**'

jobs:
  protoc:
    name: Generate stubs
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        service: ["frontend"]
        language: ["golang", "python"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate Stubs for Python
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/proto-gen.sh"
          ./proto-gen.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ matrix.language }}
